version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"  # Mapeando a porta 4000 do host para a porta 80 do contêiner
    networks:
      - desafiobackendmottu_network
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - desafiobackendmottu_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - desafiobackendmottu_network

networks:
  desafiobackendmottu_network:
    driver: bridge
